name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Call the 'build-and-push-image' job from sagal101/gitactions repository
    steps:
      - uses: sagal101/gitactions/.github/workflows/docker.yml@main
        # Replace 'docker.yml' with the correct path to your Docker workflow file

  run-node:
    runs-on: ubuntu-latest
    # Call the 'run-node' job from sagal101/gitactions repository
    steps:
      - uses: sagal101/gitactions/.github/workflows/nodejs.yml@main
        # Replace 'nodejs.yml' with the correct path to your Node.js workflow file
