name: Docker Image CIcdddd

on:
  push:
    branches:
      - main
jobs:
  build-node:
    uses: sagal101/gitactions/.github/workflows/nodejs.yml@main
    # Replace 'docker.yml' with the correct path to your Docker workflow files

  run-docker:
    uses: sagal101/gitactions/.github/workflows/docker.yml@main
    # Replace 'nodejs.yml' with the correct path to your Node.js workflow file
