name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Call the 'build-and-push-image' job from sagal101/gitactions repository
      - name: Call Docker build and push workflow from sagal101/gitactions
        uses: sagal101/gitactions/.github/workflows/nodejs.yml@main

  run-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Call the 'run-node' job from sagal101/gitactions repository
      - name: Call Docker run-node workflow from sagal101/gitactions
        uses: sagal101/gitactions/.github/workflows/docker.yml@main
