name: Docker Image CI

on:
  push:
    branches:
      - main  # Replace with your main branch name
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build-and-push-image:
    uses: sagal101/gitactions/.github/workflows/nodejs.yml@v2


  run-node:
    uses: sagal101/gitactions/.github/workflows/docker.yml/docker.yml@v2

